### ISSUE TITLE
Support for JSON files, coming to Prettier 1.5

### ISSUE THREAD

**Issue by martinschayna** [prettier/eslint-plugin-prettier#37] opened 2017-07-10 12:57 UTC
Hi

is it possible to use `prettier` via `eslint-plugin-prettier` for linting and formatting JSON files in the project?

It's nice to have specified linting and formatting glob patterns on one single place in the `eslint` run script. Now, when prettier 1.5 has builtin support for JSON files, would be great to add those files to eslint too, but eslint is unable to parse JSON files at all.

There is a plugin for linting JSON files called `elist-plugin-json` but this is completely other beast, it only checks if JSON is valid. But it's proof that it is generally possible for plugins to add JSON parser to ESlint ecosystem.

**Comment by not-an-aardvark** [comment] 2017-07-11 02:59
Similar to https://github.com/prettier/eslint-plugin-prettier/issues/29, I think that would be out of scope for this plugin. The problem is that ESLint is designed for handling JavaScript files, and it performs some actions (e.g. analyzing JavaScript variable scopes) under the assumption that a file is JavaScript. Additionally, all other ESLint rules would get run on the JSON file as if it were JavaScript, which would usually result in nonsense output. I would recommend just using `prettier` directly to lint your JSON files.

**Closed by not-an-aardvark** 2017-07-11 02:59 UTC
