### ISSUE TITLE
Issue upgrading to Prettier 3

### ISSUE THREAD

**Issue by broksonic21** [prettier/eslint-plugin-prettier#562] opened 2023-07-05 13:15 UTC
**What version of `eslint` are you using?**
8.44.0

**What version of `prettier` are you using?**
3.0.0

**What version of `eslint-plugin-prettier` are you using?**
4.2.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```
/* eslint-env node */

module.exports = {
  plugins: ["@typescript-eslint", "prettier"],

  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
  ],
  rules: {
    "prettier/prettier": "error",
  },
  settings: {
    "import/resolver": {
      typescript: {
        alwaysTryTypes: true,
      },
    },
  },
};
```

**What source code are you linting?**
private source code

**What did you expect to happen?**
Can run with prettier 3 like with prettier 2

**What actually happened?**
```
✖ eslint --quiet --fix:

Oops! Something went wrong! :(

ESLint: 8.44.0

TypeError: prettier.resolveConfig.sync is not a function
Occurred while linting REDACTED
Rule: "prettier/prettier"
    at Program (/Users/REDACTED/REDACTED/REDACTED/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:138:40)
    at ruleErrorHandler (/Users/REDACTED/REDACTED/REDACTED/node_modules/eslint/lib/linter/linter.js:1050:28)
    at /Users/REDACTED/REDACTED/REDACTED/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/REDACTED/REDACTED/REDACTED/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/REDACTED/REDACTED/REDACTED/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/REDACTED/REDACTED/REDACTED/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/REDACTED/REDACTED/REDACTED/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/Users/REDACTED/REDACTED/REDACTED/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /Users/REDACTED/REDACTED/REDACTED/node_modules/eslint/lib/linter/linter.js:1085:32
```

**Comment by shogo82148** [comment] 2023-07-05 13:22
I got same error on https://github.com/reviewdog/action-golangci-lint/pull/561#issuecomment-1621739692
The whole of log is here: https://github.com/reviewdog/action-golangci-lint/actions/runs/5464628836/jobs/9946920478?pr=561

**Comment by sandrooco** [comment] 2023-07-05 13:43
[V5 pre-release](https://github.com/prettier/eslint-plugin-prettier/releases/tag/v5.0.0-alpha.0) actually adds support for this. I'm shocked this has been in September last year... @JounQin can you provide information about the future of this package? Thanks for your work!

**Comment by ali4heydari** [comment] 2023-07-05 16:10
[`prettier.resolveConfigFile.sync` is removed from version 3 of prettier](https://prettier.io/blog/2023/07/05/3.0.0.html#change-public-apis-to-asynchronous-12574httpsgithubcomprettierprettierpull12574-12788httpsgithubcomprettierprettierpull12788-12790httpsgithubcomprettierprettierpull12790-13265httpsgithubcomprettierprettierpull13265-by-fiskerhttpsgithubcomfisker).

@sandrooco I tried version `^5.0.0-alpha.` and I got this error:
```
Cannot read properties of undefined (reading 'parsers')
Occurred while linting path/to/file:1
Rule: "prettier/prettier"
```

**Comment by ali4heydari** [comment] 2023-07-05 16:18
> [`prettier.resolveConfigFile.sync` is removed from version 3 of prettier](https://prettier.io/blog/2023/07/05/3.0.0.html#change-public-apis-to-asynchronous-12574httpsgithubcomprettierprettierpull12574-12788httpsgithubcomprettierprettierpull12788-12790httpsgithubcomprettierprettierpull12790-13265httpsgithubcomprettierprettierpull13265-by-fiskerhttpsgithubcomfisker).
> 
> @sandrooco I tried version `^5.0.0-alpha.1` and I got this error:
> 
> ```
> Cannot read properties of undefined (reading 'parsers')
> Occurred while linting path/to/file:1
> Rule: "prettier/prettier"
> ```
> 
> Dependencies:
> 
> ```
>     "@typescript-eslint/eslint-plugin": "^5.61.0",
>     "@typescript-eslint/parser": "^5.61.0",
>     "eslint": "8.44.0",
>     "eslint-config-next": "^13.4.8",
>     "eslint-config-prettier": "^8.8.0",
>     "eslint-plugin-cypress": "^2.13.3",
>     "eslint-plugin-jest": "^27.2.2",
>     "eslint-plugin-no-relative-import-paths": "^1.5.2",
>     "eslint-plugin-prettier": "^5.0.0-alpha.1",
>     "prettier": "^3.0.0",
>     "prettier-plugin-tailwindcss": "^0.3.0",
>      "typescript": "^5.1.6",
> ```

I realized that my problem is related to the `prettier-plugin-tailwindcss` package, [read more](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/176).

**Comment by skratchdot** [comment] 2023-07-05 16:39
> [V5 pre-release](https://github.com/prettier/eslint-plugin-prettier/releases/tag/v5.0.0-alpha.0) actually adds support for this. I'm shocked this has been in September last year... @JounQin can you provide information about the future of this package? Thanks for your work!

as mentioned by @sandrooco, the `v5 pre-release` fixed things for me. changing:
```
"eslint-plugin-prettier": "^4.2.1",
```
to:
```
"eslint-plugin-prettier": "^5.0.0-alpha.1",
```
in my `package.json` and re-running `npm install` fixed things for me.

**Comment by JounQin** [comment] 2023-07-06 01:18
Please use the alpha version for now, I think we need some feedback before we release the final major version.

**Comment by xiaoqiang1999** [comment] 2023-07-06 06:26
I also have this problem :
```log
Oops! Something went wrong! :(

ESLint: 8.44.0

TypeError: prettier.resolveConfig.sync is not a function
```
```json
"eslint-plugin-prettier": "^4.2.1"
```

**Comment by JounQin** [comment] 2023-07-06 06:33
@xiaoqiang1999 https://github.com/prettier/eslint-plugin-prettier/issues/562#issuecomment-1622772305

**Comment by sandrooco** [comment] 2023-07-06 07:14
Thanks for your feedback @JounQin. I was able to successfully run prettier 3.0.0 with the alpha release.

**Comment by simPod** [comment] 2023-07-06 07:57
I'm getting 

```
Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.

Oops! Something went wrong! :(

ESLint: 8.44.0

TypeError: Cannot read properties of null (reading 'map')
    at loadPlugins (file:///Users/user/.yarn/berry/cache/prettier-npm-3.0.0-7ffbcce680-10c0.zip/node_modules/prettier/index.mjs:21518:30)
    at Module.<anonymous> (file:///Users/user/.yarn/berry/cache/prettier-npm-3.0.0-7ffbcce680-10c0.zip/node_modules/prettier/index.mjs:21781:9)
    at /Users/user/project/.yarn/__virtual__/eslint-plugin-prettier-virtual-a8a43e990d/5/.yarn/berry/cache/eslint-plugin-prettier-npm-5.0.0-alpha.1-6cf9c98e88-10c0.zip/node_modules/eslint-plugin-prettier/worker.js:44:56

Process finished with exit code 2
```

**Comment by simPod** [comment] 2023-07-06 09:12
Smooth, thanks

**Comment by broksonic21** [comment] 2023-07-06 13:05
The v5.0.0-alpha.2 worked well for us in a test repo. I'd love for this to be released for real as we try to avoid using alphas in our main repos.

**Comment by cristobalgvera** [comment] 2023-07-06 16:18
When you guys think this fix will be released? It's a little bit weird being using `alpha` releases in order to avoid the breaking change introduced by Prettier.

**Comment by belgattitude** [comment] 2023-07-07 09:10
@JounQin thank you for the alpha-2 release 👍 

I've just tested on few repos and it seems to work like well. No speed regression. Link: https://github.com/belgattitude/nextjs-monorepo-example/pull/4051

**Comment by JounQin** [comment] 2023-07-07 09:40
Hope we'd release the final major version this weekend.

**Comment by huineng** [comment] 2023-07-07 13:42
i still have this issue in 5.0.0-alpha.2

but i have it in worker.js
https://github.com/prettier/eslint-plugin-prettier/blob/6878434497d4b57fdcfa91f026c45eee5ffb24be/worker.js#L38

**Comment by JounQin** [comment] 2023-07-08 01:33
@huineng No idea what's your meaning. Please provide more useful error message.


@websitevirtuoso Obviously it's a stylelint issue.

**Comment by websitevirtuoso** [comment] 2023-07-08 03:10
not related. error in stylelint plugin

**Comment by mts** [comment] 2023-07-08 19:17
[v5.0.0-alpha.0](https://github.com/papillonbits/papillonbits/commit/dd02015602f4ae5297a9e33dde9f7fa21c0272bc#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R140) seems to be working well.

**Comment by filiptammergard** [comment] 2023-07-10 08:40
Anything missing before 5.0.0 can be shipped?

**Comment by huineng** [comment] 2023-07-10 08:41
> @huineng No idea what's your meaning. Please provide more useful error message.
> 
> @websitevirtuoso Obviously it's a stylelint issue.

All good now for me

**Comment by NSeydoux** [comment] 2023-07-10 10:22
For what it's worth, `^5.0.0-alpha.2` fixes the issue for me.

**Comment by bodrovis** [comment] 2023-07-10 10:41
Same here, it works fine

**Comment by EdwardHinkle** [comment] 2023-07-10 17:22
@JounQin Hi! We're hoping to update to Prettier 3, but this is holding us back. We don't feel comfortable putting an Alpha in our system, so we're wondering when 5.0.0 is coming out? Happy to help do any testing or PRs that would help move things along

**Comment by jcurlier** [comment] 2023-07-10 21:45
+1

**Comment by sandrooco** [comment] 2023-07-11 06:45
Calm down people. Upgrading to prettier 3 isn't time critical.
It's not like the angular wrapper of Microsofts auth library which has no compatibility for Angular 15+ (community PRs were rejected, development is slow), see https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5410.

In case you never saw the xkcd about open source: https://xkcd.com/2347/ So let's be a bit more thankful for @JounQin who communicates well and puts out new releases just hours after issues are created.

**Comment by JounQin** [comment] 2023-07-11 06:51
I'm working on the final major release, but some test cases are broken due to incompatible prettier plugins like https://github.com/sveltejs/prettier-plugin-svelte/issues/317 and some issues come from package manager, so I'm migrating to pnpm at the same time.

**Closed** 2023-07-11 07:41 UTC

**Comment by filiptammergard** [comment] 2023-07-11 09:57
Thanks a lot @JounQin!

**Comment by belgattitude** [comment] 2023-07-11 10:59
Thanks a lot.

**Comment by donovanclarke** [comment] 2023-07-17 19:46
Just a note for others. 
`stylelint-prettier` @ 3.x.x and below will not work with prettier v3. You will also need to bump that package to `4.0.0`

**Comment by lehni** [comment] 2023-10-16 15:34
@ivantrave it looks like `pretty-quick` would need to be updated in order to work with prettier 3. The last release was 2 years ago. You can track the issue here:

https://github.com/azz/pretty-quick/issues/164

**Comment by ivantrave** [comment] 2023-10-20 10:46
Thanks for your comment @lehni !

For now, I downgraded to the following versions and it worked:

```
"eslint-plugin-prettier": "^4.2.1",
"prettier": "^2.8.8",
"pretty-quick": "^3.1.3",
```

Thanks

**Comment by konradbjk** [comment] 2023-10-31 11:33
Why this issue is closed, if the error is still not resolved?

For me next.js, prettier 3.0.3 and plugin 5.0.1 do not work either

**Comment by JounQin** [comment] 2023-10-31 11:36
@konradbjk Then please post another issue with runnable reproduction.

**Comment by CyxouD** [comment] 2024-05-25 11:54
Fixed after updating ESLint

```
 "eslint": "8.57.0",
 "prettier": "3.2.5",
  "eslint-plugin-prettier": "^5.1.3",
```

**Comment by IonelLupu** [comment] 2024-10-07 09:56
> Fixed after updating ESLint
> 
> ```
>  "eslint": "8.57.0",
>  "prettier": "3.2.5",
>   "eslint-plugin-prettier": "^5.1.3",
> ```

I can confirm this works for me
