### ISSUE TITLE
overrides are ignored

### ISSUE THREAD

**Issue by TobiasTimm** [prettier/eslint-plugin-prettier#68] opened 2017-11-09 07:13 UTC
**What version of `eslint` are you using?**
4.10.0
**What version of `prettier` are you using?**
1.8.1
**What version of `eslint-plugin-prettier` are you using?**
2.3.1
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
My eslint config

```js
module.exports = {
	extends: ['myCompany', 'prettier'],
	plugins: ['prettier'],
	rules: {
		'prettier/prettier': [
			'error',
			{
				printWidth: 100,
				tabWidth: 4,
				useTabs: true,
				semi: true,
				singleQuote: true,
				trailingComma: 'es5',
				bracketSpacing: true,
				jsxBracketSameLine: false,
				rangeStart: 0,
				rangeEnd: Infinity,
				proseWrap: true,
				overrides: [
					{
						files: ['*.scss', '*.css'],
						options: {
							useTabs: false,
							tabWidth: 2,
						},
					},
					{
						files: ['*.json'],
						options: {
							useTabs: false,
							tabWidth: 2,
						},
					},
					{
						files: ['*.md'],
						options: {
							useTabs: false,
							tabWidth: 4,
						},
					},
				],
			},
		],
	},
};
```
**What source code are you linting?**
JavaScript, CSS/SCSS, Markdown, JSON
**What did you expect to happen?**
A valid eslint+prettier config
**What actually happened?**

The eslint output

```sh
● Validation Warning:

  Unknown option "proseWrap" with value true was found.
  This is probably a typing mistake. Fixing it will remove this message.

● Validation Warning:

  Unknown option "overrides" with value [{"files": ["*.scss", "*.css"], "options": {"tabWidth": 2, "useTabs": false}}, {"files": ["*.json"], "options": {"tabWidth": 2, "useTabs": false}},{"files": ["*.md"], "options": {"tabWidth": 4, "useTabs": false}}] was found.
  This is probably a typing mistake. Fixing it will remove this message.

● Validation Warning:

  Unknown option "proseWrap" with value true was found.
  This is probably a typing mistake. Fixing it will remove this message.

● Validation Warning:

  Unknown option "overrides" with value [{"files": ["*.scss", "*.css"], "options": {"tabWidth": 2, "useTabs": false}}, {"files": ["*.json"], "options": {"tabWidth": 2, "useTabs": false}},{"files": ["*.md"], "options": {"tabWidth": 4, "useTabs": false}}] was found.
  This is probably a typing mistake. Fixing it will remove this message.

```

**Comment by ikatyang** [comment] 2017-11-09 07:25
- See prettier/prettier#3216 for the `proseWrap` warning.
- The `overrides` option is only available in the config file (`.prettierrc`, etc.).

**Comment by not-an-aardvark** [comment] 2017-11-09 08:34
Closing because this is working as intended based on https://github.com/prettier/eslint-plugin-prettier/issues/68#issuecomment-343069185

**Closed by not-an-aardvark** 2017-11-09 08:34 UTC
