### ISSUE TITLE
Definition for rule 'prettier/prettier' was not found  prettier/prettier

### ISSUE THREAD

**Issue by paulcedrick** [prettier/eslint-plugin-prettier#20] opened 2017-05-12 04:21 UTC
Hi,

We're having trouble integrating prettier with eslint. We used `eslint-plugin-prettier` together with `eslint-configure-prettier`. Here's the content of the `package.json` that we use
```
{
  ...
  "scripts": {
    ...,
    "lint": "./node_modules/.bin/eslint .",
   ...
  },
  "dependencies": {
    ...
  },
  "devDependencies": {
    ...,
    "eslint": "^3.17.1",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-config-loopback": "^4.0.0",
    "eslint-config-prettier": "^2.0.0",
    "eslint-import-resolver-babel-module": "^3.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-prettier": "^2.0.1",
    ...,
    "prettier": "^1.3.1",
    "prettier-eslint": "^6.2.0",
    "prettier-eslint-cli": "^3.4.3",
    ...
  },
  "repository": {
    "type": "",
    "url": ""
  },
 ...
}
```
Here is our `.eslintrc` config file
```
{
  "parser": "babel-eslint",
  "extends": [
    "airbnb/base",
    "prettier"
  ],
  "parserOptions": {
    "ecmaVersion": 8,
    "sourceType": "module"
  },
  "env": {
    "es6": true,
    "node": true
  },
  "rules": {
    "prettier/prettier": "error",
    "arrow-parens": [
      "error",
      "always"
    ],
    "arrow-body-style": [
      2,
      "as-needed"
    ],
    "comma-dangle": [
      2,
      "always-multiline"
    ],
    "import/imports-first": 0,
    "import/newline-after-import": 0,
    "import/no-dynamic-require": 0,
    "import/no-extraneous-dependencies": 0,
    "import/no-named-as-default": 0,
    "import/prefer-default-export": 0,
    "indent": [
      2,
      2,
      {
        "SwitchCase": 1
      }
    ],
    "linebreak-style": [
      2,
      "unix"
    ],
    "new-cap": [
      2,
      {
        "properties": false
      }
    ],
    "no-unused-vars": [
      2,
      {
        "vars": "all",
        "args": "after-used"
      }
    ],
    "no-use-before-define": [
      2
    ],
    "no-trailing-spaces": [
      2
    ],
    "quotes": [
      2,
      "single"
    ],
    "semi": [
      2,
      "always"
    ],
    "wrap-iife": [
      2,
      "outside"
    ],
    "strict": [
      2,
      "global"
    ],
    "brace-style": 2,
    "block-spacing": [
      2,
      "always"
    ],
    "keyword-spacing": [2, {"before": true, "after": true, "overrides": {}}],
    "space-before-blocks": 2,
    "space-before-function-paren": [2, {"anonymous": "always", "named": "never"}],
    "comma-spacing": [2, {"before": false, "after": true}],
    "comma-style": [2, "last"],
    "no-lonely-if": 2,
    "array-bracket-spacing": [2, "never"],
    "no-spaced-func": [2],
    "space-in-parens": [2, "never"],
    "space-infix-ops": 2
  },
  "settings": {
    "import/resolver": {
      "babel-module": {}
    }
  },
  "globals": {
    "after": true,
    "afterEach": true,
    "before": true,
    "beforeEach": true,
    "describe": true,
    "it": true
  }
}
```

Everytime we start linting, it says that `Definition for rule 'prettier/prettier' was not found  prettier/prettier`. Do we miss some dependencies for it? :)

**Comment by not-an-aardvark** [comment] 2017-05-12 04:33
You have `"prettier"` in an `extends` list. Instead, you should put it in a `plugins` list.

```json
{
  "extends": [
    "airbnb/base"
  ],
  "plugins": [
    "prettier"
  ]
}
```

**Comment by not-an-aardvark** [comment] 2017-05-19 02:55
Closing because I think this is working as intended.

**Closed by not-an-aardvark** 2017-05-19 02:55 UTC

**Comment by arulrajnet** [comment] 2017-08-08 20:21
I am getting similar error

- Create react-app with https://github.com/facebookincubator/create-react-app
- emit the config files
- Install prettier, eslint-plugin-prettier and eslint-config-prettier

Here is the `.eslintrc`

```
{
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "node": true
  },
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true,
      "classes": true,
      "defaultParams": true
    }
  },
  "rules": {
    "no-const-assign": 1,
    "no-extra-semi": 0,
    "semi": 0,
    "no-fallthrough": 0,
    "no-empty": 0,
    "no-mixed-spaces-and-tabs": 1,
    "no-redeclare": 0,
    "no-this-before-super": 1,
    "no-undef": 1,
    "no-unreachable": 1,
    "no-unused-vars": 1,
    "no-use-before-define": 0,
    "constructor-super": 1,
    "curly": 0,
    "eqeqeq": 1,
    "func-names": 1,
    "valid-typeof": 1,
    "prettier/prettier": 1,
    // overrideing recommented rules
    "react/prop-types": 1,
    "no-console": 1
  },
  "extends": [
    "eslint-config-prettier",
    "eslint:recommended",
    "plugin:react/recommended"
  ],
  "plugins": [
    "eslint-plugin-prettier",
    "react",
    "jsx-a11y",
    "import"
  ]
}
```

- If I run eslint command its finds the formatting issues successfully
- If I start the dev server with `npm run start` its just hangs.

**Comment by zerostyle** [comment] 2017-12-12 02:32
Having the same issue as above.

**Comment by mschipperheyn** [comment] 2019-03-30 12:52
@arulrajnet where is the `"plugins": ["prettier"`?

**Comment by SnekNOTSnake** [comment] 2020-08-24 01:05
My case was I forgot to install the `prettier` package itself.

**Comment by yumemi-omi** [comment] 2020-09-08 09:50
My minimal setup is working well.
```
module.exports = {
  "plugins": [
    "prettier",
  ],
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "prettier",
  ],
  rules: {
    "prettier/prettier": "error",
  }
}
```

**Comment by clemenger** [comment] 2020-12-22 20:35
In my case the only reference to it was at the top of one of our files:
`/* eslint-disable prettier/prettier */`
Ironically, a comment to disable the rule caused the lookup error.  Removing this line fixed it.

**Comment by dimaslanjaka** [comment] 2021-05-30 19:47
My Config Working Like a Charm
```js
module.exports = {
    parser: "@typescript-eslint/parser", // Specifies the ESLint parser
    env: {
        browser: true,
        commonjs: true,
        es6: true,
        jquery: true,
    },
    parserOptions: {
        parser: "babel-eslint",
        ecmaVersion: 2020, // Allows for the parsing of modern ECMAScript features
        sourceType: "module", // Allows for the use of imports
    },
    plugins: ["prettier"],
    extends: ["plugin:vue/vue3-recommended", "plugin:@typescript-eslint/recommended", "prettier"],
    rules: {
        "prefer-rest-params": "off",
        "@typescript-eslint/explicit-function-return-type": "off",
        "@typescript-eslint/indent": ["warn", 4],
        "@typescript-eslint/no-this-alias": "off",
        "@typescript-eslint/no-unused-vars": "warn",
        // disable any type error warning
        "@typescript-eslint/no-explicit-any": "off",
        // Disable `export function functionName()....`
        "@typescript-eslint/explicit-module-boundary-types": "off",
        "@typescript-eslint/ban-types": "off",
        "@typescript-eslint/triple-slash-reference": "off",

        "no-const-assign": 1,
        "no-extra-semi": 0,
        semi: 0,
        "no-fallthrough": 0,
        "no-empty": 0,
        "no-mixed-spaces-and-tabs": 1,
        "no-redeclare": 0,
        "no-this-before-super": 1,
        "no-undef": 1,
        "no-unreachable": 1,
        "no-unused-vars": 1,
        "no-use-before-define": 0,
        "constructor-super": 1,
        curly: 0,
        eqeqeq: 1,
        "func-names": 1,
        "valid-typeof": 1,
        "prettier/prettier": 1,
        "no-console": 1,
    },
};
```

**Comment by mklimkin0190** [comment] 2021-07-16 07:56
Experiencing the issue with the following .eslintrc.js (note 'prettier' in both plugins and extends):

```Javascript
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: 'tsconfig.json',
    sourceType: 'module',
  },
  plugins: ['@typescript-eslint/eslint-plugin', 'prettier'],
  extends: [
    'prettier',
    'eslint:recommended',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:react/recommended',
    'plugin:prettier/recommended',
  ],
  root: true,
  env: {
    node: true,
    jest: true,
  },
  rules: {...},
}
```

**Comment by mehran-m** [comment] 2021-11-12 01:51
If you have configured your eslintrc correctly and your editor still shows the error, try to restart your editor.
I closed my VSCode and opened it again, all the previous errors were gone after that.

**Comment by pfouny** [comment] 2022-03-24 16:07
> If you have configured your eslintrc correctly and your editor still shows the error, try to restart your editor. I closed my VSCode and opened it again, all the previous errors were gone after that.

it's working

**Comment by SeiwonPark** [comment] 2023-02-23 07:47
Here's my config

**Run first**
```bash
$ npm i -D eslint eslint-plugin-prettier eslint-config-prettier prettier
```

**Files**
`.eslintrc.js`
```javascript
module.exports = {
  env: {
    es2021: true,
    node: true,
  },
  extends: ['prettier'],
  overrides: [],
  plugins: ['prettier'],
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  rules: {
    'prettier/prettier': 'warn',
  },
};
```

`.prettierrc` (Optional)
```json
{
  "singleQuote": true,
  "trailingComma": "all"
}
```

**Comment by felipemenezes98** [comment] 2023-10-18 20:01
> If you have configured your eslintrc correctly and your editor still shows the error, try to restart your editor. I closed my VSCode and opened it again, all the previous errors were gone after that.

Yeah, that worked for me. Thanks!
