### ISSUE TITLE
Non-JS support (Specifically Markdown)

### ISSUE THREAD

**Issue by azz** [prettier/eslint-plugin-prettier#67] opened 2017-11-08 12:13 UTC
Prettier 1.8 has Markdown support. It also formats code blocks with Markdown.

Would it make sense to support Markdown in this plugin using a [processor](https://eslint.org/docs/developer-guide/working-with-plugins#processors-in-plugins)? Perhaps it could even work alongside [eslint-plugin-markdown](https://github.com/eslint/eslint-plugin-markdown)?

I haven't tried yet, but I imagine eslint-plugin-markdown will already work with this plugin to provide errors and fixes for the embedded code blocks, but maybe fixes for the Markdown itself could be supported too?

**Comment by not-an-aardvark** [comment] 2017-11-09 08:34
I think this is similar to https://github.com/prettier/eslint-plugin-prettier/issues/29 and https://github.com/prettier/eslint-plugin-prettier/issues/37. The problem is that in order for the `prettier` rule on markdown, the markdown text would have to be parsable as JavaScript. Also, if the markdown was parsed successfully (e.g. by using a custom parser to create an AST), then all the other active ESLint rules would be run on the markdown too, which would probably result in errors/nonsensical output because the markdown isn't JavaScript.

I'm not sure processors would work well here either, because processors can only extract JavaScript snippets from text and have ESLint lint them. It still can't make ESLint handle non-JavaScript text.

**Comment by not-an-aardvark** [comment] 2017-12-07 04:31
Closing because I don't think this is feasible.

**Closed by not-an-aardvark** 2017-12-07 04:31 UTC
