### ISSUE TITLE
conflict with vue/max-attributes-per-line eslint rule

### ISSUE THREAD

**Issue by kepi0809** [prettier/eslint-plugin-prettier#289] opened 2020-04-23 14:51 UTC
Hi guys, 

great work with this plugin, unfortunately I found a bug that I'm hoping it would be possible to fix. So basically prettiers `printWidth` conflicts with vue's `vue/max-attributes-per-line` rule. Originally I was using both eslint & prettier the only reason I am here because wanted to try it with prettier being integrated into eslint so that mb eslint could override this printwidth enfroce somehow of prettier. 

Before added the plugin I was just running with the IDE both eslint & prettier on save and in that case prettier has the last word which ends up being like I'll describe later. 

Could you tell if it would be possible somehow to get this working? Turning off the `vue/max-attributes-per-line` rule wouldn't be a good solution to me, because my team wants to stick to it (while still having higher printwidth). So I was thinking of a solution that would take both in calculation and the `vue/max-attributes-per-line` rule would decide how it should look like.

**What version of `eslint` are you using?** 
v6.8.0

**What version of `prettier` are you using?** 
2.0.5

**What version of `eslint-plugin-prettier` are you using?**
v3.1.3

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

#### .eslintrc.js: 
```js
module.exports = {
    root: true,
    env: {
        browser: true,
        es6: true,
    },
    globals: {
        Atomics: 'readonly',
        SharedArrayBuffer: 'readonly',
    },
    plugins: ['vue', 'graphql', 'prettier'],
    extends: ['plugin:prettier/recommended', 'plugin:vue/recommended', '@vue/airbnb', 'prettier', 'prettier/vue'],
    rules: {
        'no-prototype-builtins': 'off',
        // Only allow `console.log` in development
        'no-console': process.env.PRE_COMMIT || process.env.VUE_APP_HM_APPLICATION_ENV === 'production' ? ['error', { allow: ['warn', 'error'] }] : 'off',
        // Only allow debugger in development
        'no-debugger': process.env.PRE_COMMIT || process.env.VUE_APP_HM_APPLICATION_ENV === 'production' ? 'error' : 'off',
        'no-param-reassign': ['error', { props: true }],
        'prefer-destructuring': ['error', { object: false, array: false }], //* const name = supplier.name; can be used
        'vue/name-property-casing': ['error', 'PascalCase'], //* Component name should be in PascalCase.
        'vue/order-in-components': ['error'], //* order of component options like `name`, `methods` etc.
        'vue/component-name-in-template-casing': ['error', 'kebab-case'], //* Use `<my-component />` in templates
        'vue/prop-name-casing': ['error', 'camelCase'], //* Props should be named in camelCase in JS, but
        'vue/attribute-hyphenation': ['error', 'always', { ignore: ['viewBox'] }], //* use `<... my-prop="" />` in templates.
        'vue/match-component-file-name': ['error', { extensions: ['vue'], shouldMatchCase: true }], //* component name and filename should match
        'graphql/template-strings': ['error', { env: 'apollo', schemaJson: require('./schema.json') }],
        'no-underscore-dangle': ['error', { allow: ['__typename'] }],
        'template-curly-spacing': 'off',
        'import/order': 'off', // https://github.com/benmosher/eslint-plugin-import/issues/1306
        "vue/max-attributes-per-line": ["error", {
            "singleline": 4,
            "multiline": {
              "max": 1,
              "allowFirstLine": false
            }
        }]
    },
    overrides: [
        {
            files: ['*.vue'],
            rules: {
                indent: 'off',
                'vue/script-indent': [
                    'error',
                    4,
                    {
                        baseIndent: 1,
                    },
                ],
            },
        },
    ],
    env: {},
    parserOptions: {
        ecmaVersion: 2018,
        sourceType: 'module',
        extends: 'standard',
        parser: 'babel-eslint',
    },
};
```
#### .prettierrc.js: 
```js
module.exports = {
    printWidth: 160,
    tabWidth: 4,
    singleQuote: true,
    htmlWhitespaceSensitivity: 'strict',
    vueIndentScriptAndStyle: true,
    overrides: [
        {
            files: ['*.scss', '*.css', '*.json', '*.md'],
            options: {
                tabWidth: 2
            }
        }
    ]
};
```

**What source code are you linting?**
`.vue` and `.js` files mainly.
an example: 
```vue
            <slot name="table" :rows="tableData" :sorting="sorting" :onSort="handleSorting" :loading="$apollo.queries.query.loading" />
```

**What did you expect to happen?**
```vue
            <slot
                name="table"
                :rows="tableData"
                :sorting="sorting"
                :onSort="handleSorting"
                :loading="$apollo.queries.query.loading"
            />
```
**What actually happened?**
_Note: also the indent is wrong (0 spaces)_ 
```vue
            <slot
name="table"
:rows="tableData" :sorting="sorting" :onSort="handleSorting" :loading="$apollo.queries.query.loading" />
```

Looking forward to hearing from you!

Kepi

**Comment by Tinoooo** [comment] 2020-04-30 09:34
This is a duplicate of #94 
@kepi0809 Do you use any temporary fix/workaround?

**Comment by kepi0809** [comment] 2020-04-30 09:39
Hi @Tinoooo, thanks for the fast answer, no unfortunately I couldn't find a workaround, a better result is to disable this eslint rule of vue and decrease printWidth between 100-120. Other than that I couldn't make it better

**Comment by Tinoooo** [comment] 2020-04-30 09:43
Okay. My workaround is to stick with prettier 1.14.3. But it of course leads to other problems.

**Comment by kepi0809** [comment] 2020-04-30 09:44
Can you tell me what are the other problems? Wouldn't it be possible to somehow get this working with that version of prettier and maybe some extra rules of eslint?

**Comment by Tinoooo** [comment] 2020-04-30 09:47
It's been a while since I configured prettier for me, so I don't remember them well. But they occured because of missing features and typescript compatibility in the older version of prettier.

**Comment by lydell** [comment] 2020-06-05 17:04
Prettier is simply not compatible with `vue/max-attributes-per-line`. There’s nothing eslint-plugin-prettier is able to do about that. Here are your choices:

- Turn off `vue/max-attributes-per-line`.
- Use [prettier-eslint](https://github.com/prettier/prettier-eslint).
- Stop using Prettier.
- Fork Prettier.
- Give a thumbs-up to https://github.com/prettier/prettier/issues/5501.

**Closed by lydell** 2020-06-05 17:04 UTC

**Comment by moeinghasemi381** [comment] 2023-01-18 12:13
Hi everyone, this worked for me:
set 'singleAttributePerLine': true in the prettier config file (e.g .prettierrc) and everything gets ok.
