### ISSUE TITLE
error: no member named 'ForceSet' in 'v8::Object'

### ISSUE THREAD

**Issue by techhysahil** [prettier/eslint-plugin-prettier#91] opened 2018-05-11 15:15 UTC
Installation error: 
<img width="1280" alt="screen shot 2018-05-11 at 8 40 03 pm" src="https://user-images.githubusercontent.com/7847056/39931643-a6fd1286-555b-11e8-960a-03608eadcc7e.png">

"eslint": "^3.0.1",
node : v10.0.0

**Comment by not-an-aardvark** [comment] 2018-05-11 16:03
Hi, thanks for the report. Could you elaborate on what you were doing that caused this error? `eslint-plugin-prettier` doesn't have any C++ as far as I know, so I'm not sure what would cause this error.

**Comment by techhysahil** [comment] 2018-05-11 20:39
Two days back i got new system. So, I had installed node using brew. 

After that for code formatting i tried installing "eslint-plugin-prettier" && "prettier" and it was giving me error while installation.

Later i downgrade node to 8.x.x and it works.

**Comment by not-an-aardvark** [comment] 2018-05-11 20:41
Could you give more details? What command are you using to install the plugins? You may want to report a bug on your package manager instead.

**Comment by phpguru** [comment] 2018-05-15 19:43
We don't use prettier in our project, but something else caused this same error which brought me to here and then a bunch of other places searching for a fix. I think it may be `node-gyp` that has a dependency to `nan` - the error if I'm not mistaken is `V8::Object` deprecations that worked in Node v8x-v9x but not in Node v10x. As a workaround I found that "downgrading" to v9.11.1 using [node version manager](https://github.com/tj/n) got my front end building again.

**Comment by jesstelford** [comment] 2018-05-16 00:34
I had this error because [Kerberos doesn't support node 10 yet](https://github.com/mongodb-js/kerberos/issues/72), and had to downgrade to node 8 before compilation would succeed.

_PS: Sorry for spamming this issue @prettier-devs - it's the top result on Google, so more info here might help future devs_.

**Comment by not-an-aardvark** [comment] 2018-05-16 01:14
Thanks for the info. I'm going to close this issue since it doesn't seem to be a problem with `eslint-plugin-prettier`, but feel free to continue the discussion. For anyone else that comes across this issue, it seems like the problem is occurring when some native dependencies aren't compatible with Node 10.

**Closed by not-an-aardvark** 2018-05-16 01:14 UTC
