### ISSUE TITLE
.prettierc overrides are ignored

### ISSUE THREAD

**Issue by QuentinRoy** [prettier/eslint-plugin-prettier#59] opened 2017-10-09 12:47 UTC
It seems the plugin ignores prettier's overrides options. E.g. the following `.prettierc` fails for the directory `build_tools`:

```yaml
{
  "trailingComma": "all",
  "overrides": [
    {
      "files": "build_tools/*.js",
      "options": {
        "trailingComma": "es5"
      }
    }
  ]
}
```

**Comment by not-an-aardvark** [comment] 2017-10-10 07:16
This seems like it might be an issue with `prettier`'s API rather than `eslint-plugin-prettier`. `eslint-plugin-prettier` only uses prettier's API [here](https://github.com/prettier/eslint-plugin-prettier/blob/62085cc01731847d66456e089a7529d25dcb1254/eslint-plugin-prettier.js#L357) to get a config -- it doesn't do any config resolution itself.

**Comment by not-an-aardvark** [comment] 2017-10-10 07:28
Also, I noticed that you mentioned the name `.prettierc` in the issue, but I think the filename should actually be `.prettierrc`. I'm not sure if this was a typo, but presumably giving the file the wrong name would cause it to get ignored entirely.

**Comment by QuentinRoy** [comment] 2017-10-10 08:31
The odd thing is that prettier by itself works as expected.
E.g. if I successively run:
```sh
npx prettier --write build_tools/**/*.js  # OK, files modified as expected
npx eslint build_tools/**/*.js  # Nope.
```

**Comment by QuentinRoy** [comment] 2017-10-10 08:33
If it is useful, here is my `.eslintrc.yml`:

```yaml
root: true
extends:
  - airbnb
  - prettier
  - prettier/react
plugins:
  - prettier
rules:
  prettier/prettier:
    - error
overrides:
  - files:
    - build_tools/**
    env:
      node: true
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
```

**Comment by not-an-aardvark** [comment] 2017-10-10 21:33
This is caused by https://github.com/prettier/prettier/issues/3005.

**Comment by zimme** [comment] 2017-12-05 13:04
I guess this should be resolved by now?

**Comment by not-an-aardvark** [comment] 2018-01-16 05:15
Agreed, I think this has been fixed since https://github.com/prettier/prettier/issues/3005 is closed.

**Closed by not-an-aardvark** 2018-01-16 05:15 UTC
Labels: blocked, bug
