### ISSUE TITLE
Replace ' ' with  Return Symbol (⏎······'code',⏎)

### ISSUE THREAD

**Issue by formatkaka** [prettier/eslint-plugin-prettier#71] opened 2017-11-30 07:58 UTC
**What version of `eslint` are you using?**
4.10

**What version of `prettier` are you using?**
1.8.2

**What version of `eslint-plugin-prettier` are you using?**
2.3.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```javascript
{
  "extends": ["airbnb", "prettier"],
  "plugins": ["prettier"],
  "parserOptions": {
    "ecmaVersion": 2016,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "es6": true,
    "browser": true,
    "node": true
  },
  "globals": {
    "_": true
  },
  "rules": {
    "no-console": 0,
    "prefer-template": 0,
    "no-underscore-dangle": 0,
    "jsx-a11y/anchor-is-valid": [
      "error",
      {
        "components": ["Link"],
        "specialLink": ["to", "hrefLeft", "hrefRight"],
        "aspects": ["noHref", "invalidHref", "preferButton"]
      }
    ],
    "prettier/prettier": ["error", { "singleQuote": true }]
  }
}
```

**What source code are you linting?**
`self.sup.addEventListener('change-background', self.changeBackground);`

**What did you expect to happen?**
Did not expect an error because my sublime Jsprettier extension does not make any changes to the written code. I tried the code on prettier.io website and that too didn't change the formatting.

**What actually happened?**
Error :   
`Replace 'change-background',·self.changeBackground with ⏎······'change-background',⏎······self.changeBackground⏎····`

On running `eslint --fix` it fixes the code to 
```javascript
self.el.sceneEl.addEventListener(
  'change-background',
  self.changeBackground
);
```

But on formatting the file in sublime by saving, it does not format in the above shown manner, which results in the error.

I want to remove this error and use the original style of code I have written, but not finding a rule to disable this.

Thanks

**Comment by not-an-aardvark** [comment] 2017-12-07 04:31
Thanks for the report. However, I can't reproduce this issue on the command line:

```
$ echo "self.sup.addEventListener('change-background', self.changeBackground);" | node_modules/.bin/eslint --no-eslintrc --stdin --plugin=prettier --rule 'prettier/prettier: [error, {singleQuote: true}]'
```

Are you sure the config file that you posted is the only config file being applied to your code?

**Comment by not-an-aardvark** [comment] 2018-01-13 03:04
Closing because I can't reproduce this issue. Feel free to open another issue if you're still encountering this.

**Closed by not-an-aardvark** 2018-01-13 03:04 UTC

**Comment by RobertJGabriel** [comment] 2018-05-15 01:06
Getting this issue too.

<img width="681" alt="screen shot 2018-05-14 at 8 05 49 pm" src="https://user-images.githubusercontent.com/6218780/40030805-3a0d4a8e-57b2-11e8-995e-206f3e0a677d.png">

**Comment by not-an-aardvark** [comment] 2018-05-15 01:11
@RobertJGabriel Keep in mind that prettier might be inserting a linebreak into your code because the line is long.

If you think there is a bug in `eslint-plugin-prettier`, please feel free to create a new issue.

**Comment by polpenaloza** [comment] 2018-10-16 20:31
I don't think it's a bug, but it's annoying to format the code when there is no need to do so, and i can't find the rule that is asking me to "Fix" it.
![image](https://user-images.githubusercontent.com/4138333/47045484-4be6fa80-d169-11e8-8efa-fc07de71f6e9.png)
Anyone here? what is the rule we need to disable?

**Comment by not-an-aardvark** [comment] 2018-10-16 20:36
If you don't want your code to be formatted, you can disable the `prettier/prettier` rule (and also consider removing `eslint-plugin-prettier`, since that rule is the entire functionality of this project).

If you just want to disable warnings in an editor while still having the rule enabled on the command line, you can look into your editor settings -- I think some editor plugins support ignoring warnings from certain rules.

**Comment by Ale-cc** [comment] 2019-08-06 09:34
I solved by this issue [https://github.com/prettier/eslint-plugin-prettier/issues/42](url)

**Comment by crhistianramirez** [comment] 2019-11-09 17:40
@Ale-cc  that issue doesnt seem to exist

**Comment by Andreagar28** [comment] 2021-03-31 19:41
same issue here.
