### ISSUE TITLE
"error Delete `⏎` prettier/prettier" in .vue files 

### ISSUE THREAD

**Issue by ImreC** [prettier/eslint-plugin-prettier#114] opened 2018-09-28 12:35 UTC
I am using the create-nuxt-app to create a nuxt 2.0 application with prettier included. I am running vscode on a windows machine. My package.json looks like this (nothing changed compared to the template):

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "Test",
  "author": "",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "cross-env": "^5.2.0",
    "nuxt": "^2.0.0",
    "@nuxtjs/axios": "^5.0.0"
  },
  "devDependencies": {
    "nodemon": "^1.11.0",
    "babel-eslint": "^8.2.1",
    "eslint": "^5.0.1",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-vue": "^4.0.0",
    "eslint-config-prettier": "^3.1.0",
    "eslint-plugin-prettier": "2.6.2",
    "prettier": "1.14.3"
  }
}
```

The error "error Delete `⏎` prettier/prettier" in .vue files" still persists. I tried to search for a solution, but the only thing that I could find was this old issue (https://github.com/prettier/eslint-plugin-prettier/issues/42) which stated that the issue was resolved over a year ago. Guess it's back?

**Comment by ImreC** [comment] 2018-09-28 12:47
Updating all related packages does not resolve the issue. package.json now looks like this:

```
{
  "name": "silksage-frontend",
  "version": "1.0.0",
  "description": "The SilkSage platform frontend",
  "author": "Imre Gelens",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "cross-env": "^5.2.0",
    "nuxt": "^2.0.0",
    "@nuxtjs/axios": "^5.0.0"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.1",
    "eslint": "^5.6.0",
    "eslint-config-prettier": "^3.1.0",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-prettier": "^2.7.0",
    "eslint-plugin-vue": "^4.7.1",
    "nodemon": "^1.11.0",
    "prettier": "^1.14.3"
  }
}
```

**Comment by BPScott** [comment] 2018-09-28 21:52
Hi @ImreC, I am not able to reproduce this issue. Can you please provide an example vue file that exhibits this issue.

The following works for me:

`yarn create nuxt-app nuxt-app` And use the following options:

? Project name nuxt-app
? Project description My prime Nuxt.js project
? Use a custom server framework none
? Use a custom UI framework none
? Choose rendering mode Universal
? Use axios module no
? Use eslint yes
? Use prettier yes
? Author name Ben Scott
? Choose a package manager npm

`cd nuxt-app`

`yarn run lint` - Initially reports errors, but should be fixed once https://github.com/nuxt/create-nuxt-app/pull/100 is released

`yarn run lint --fix` - Fixes errors

`yarn run lint` - No more errors reported

**Comment by DimaFromCanada** [comment] 2018-09-30 08:41
Same issue here on a fresh setup with create-nuxt-app

? Project name foo
? Project description foobar
? Use a custom server framework Express
? Use a custom UI framework ElementUi
? Choose rendering mode Universal
? Use axios module yes
? Use eslint yes
? Use prettier yes
? Author name Baz
? Choose a package manager npm

**Comment by ImreC** [comment] 2018-10-01 08:19
@BPScott I tried your solution. It actually makes it worse. Error output:

```
path\to\nuxt\nuxt.config.js
  16:12  error  Replace `⏎······{·rel:·'icon',·type:·'image/x-icon',·href:·'/favicon.ico'·}⏎····` with `{·rel:·'icon',·type:·'image/x-icon',·href:·'/favicon.ico'·}`  prettier/prettier
  29:9   error  Delete `⏎··`                                                                                                                                          prettier/prettier
  35:13  error  Delete `⏎··`                                                                                                                                          prettier/prettier

path\to\nuxt\pages\index.vue
  36:1  error  Delete `⏎`  prettier/prettier

✖ 4 problems (4 errors, 0 warnings)
  4 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by ImreC** [comment] 2018-10-01 08:19
Create nuxt app version: 2.1.1

**Comment by harleytouch** [comment] 2018-10-05 03:39
I had the same issue mentioned in the original post. 
The error message appears to be complaining about a line break at line 36 of the pages/index.vue.
So I deleted that line break, restarted the local server and all good now.

**Comment by BPScott** [comment] 2018-10-05 05:48
@BPScott thanks for looking into this and sorry for not testing this earlier. I tried your solution. It increases the amount of errors from 1 to 4. Error output:

Yep that's what I saw to on my initial run of `yarn run lint`. Does running `yarn run lint --fix` get rid of the errors?

**Comment by ImreC** [comment] 2018-10-05 07:54
@BPScott I followed your instructions exactly, but I was using npm. I just found out that npm has a different way of passing arguments to scripts than yarn. On npm it is `npm run lint -- --fix`. This SO comment captures my sentiment perfectly:

![image](https://user-images.githubusercontent.com/9742684/46522846-2feb7b00-c884-11e8-87de-c937256d5915.png)

I feel very dumb now, but it's how we learn I guess. Thanks for looking into this!

**Closed** 2018-10-05 15:03 UTC

**Comment by gentunian** [comment] 2018-10-08 14:38
This problem exists and has to do with the newlines inserted. 

Take for example this error:

```
code/nodejs/nuxt.js/foo/pages/index.vue
  36:1  error  Delete `⏎`  prettier/prettier
```

Then, go to line 36. You will notice a newline between the `style` tag and the styles definitions. Remove that line and error is gone.
```
<style>

.container {
```

If you have this error in another file, just follow the same procedure.

**Comment by microcipcip** [comment] 2018-10-08 22:14
I have this error but don't have any newline between style and the class and it doesn't go away.

**Comment by harleytouch** [comment] 2018-10-08 22:22
> I have this error but don't have any newline between style and the class and it doesn't go away.

I had to restart the local server for it to pick up the change.

**Comment by gugacavalieri** [comment] 2018-10-09 17:17
@gentunian that did the trick for me ! :+1:

**Comment by AndrianD** [comment] 2018-10-13 23:19
> This problem exists and has to do with the newlines inserted.
> 
> Take for example this error:
> 
> ```
> code/nodejs/nuxt.js/foo/pages/index.vue
>   36:1  error  Delete `⏎`  prettier/prettier
> ```
> Then, go to line 36. You will notice a newline between the `style` tag and the styles definitions. Remove that line and error is gone.
> 
> ```
> <style>
> 
> .container {
> ```
> If you have this error in another file, just follow the same procedure.

Thank you for the trick!

**Comment by ktiedt** [comment] 2018-10-29 20:20
For other's reference, I had a similar, but different error.

>    89:1  error  Delete `··`                           prettier/prettier

Caused by this code...
```
<script>
  export default {
```
The complaint? export should not be indented, so highlighting the codeblock and removing 1 indent fixed all the errors (17 in total for default.vue)

**Comment by 0njzy0** [comment] 2018-12-15 17:31
I have encountered this problem in the template section of the vue file and it has now been resolved. Let's share how I used eslint and perttier in the vue project.

This is my .eslintrc.js
```js
module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint',
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true
    }
  },
  env: {
    es6: true,
    node: true
  },
  extends: [
    'standard',
    'plugin:vue/recommended',
    'prettier',
    'prettier/standard',
    'prettier/vue'
  ],
  plugins: ['standard', 'vue', 'prettier'],
  rules: {
    'prettier/prettier': [
      'error',
      {
        arrowParens: 'avoid',
        bracketSpacing: true,
        endOfLine: 'auto',
        htmlWhitespaceSensitivity: 'ignore',
        jsxBracketSameLine: false,
        jsxSingleQuote: false,
        semi: false,
        singleQuote: true,
        tabWidth: 2,
        trailingComma: 'none',
        useTabs: false
      }
    ],
    'vue/html-self-closing': [
      'error',
      {
        html: {
          void: 'any'
        }
      }
    ],
    'vue/no-use-v-if-with-v-for': ['off'],
    'vue/component-name-in-template-casing': ['off'],
    'vue/no-unused-components': ['off'],
    eqeqeq: ['off'],
    'no-new': ['off']
  }
}
```
Because I didn't configure the prettierrc file separately, I put the prettier configuration item in the eslint configuration file. The option to solve the **error Delete `⏎`** problem is **htmlWhitespaceSensitivity: 'ignore'.**

This is my vetur and eslint configion in vscode:

```json
  "prettier.disableLanguages": [],
  "prettier.eslintIntegration": true,
  "eslint.enable": false,
  "eslint.autoFixOnSave": true,
  "eslint.alwaysShowStatus": true,
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    {
      "language": "vue",
      "autoFix": true
    }
  ],
  "vetur.format.defaultFormatter.html": "none",
  "vetur.format.defaultFormatter.css": "none",
  "vetur.format.defaultFormatter.js": "none",
  "vetur.format.defaultFormatter.less": "none",
  "vetur.format.defaultFormatter.postcss": "none",
  "vetur.format.defaultFormatter.scss": "none",
  "vetur.format.defaultFormatter.stylus": "none",
  "vetur.format.defaultFormatter.ts": "none",
  "vetur.validation.template": false,
```

**Comment by jmartinezuk** [comment] 2019-01-08 15:02
`npm run lint -- --fix` did it for me

**Comment by MuhammadSayedMorsi** [comment] 2019-01-16 17:36
hi .. i have the same issue with every component i write .. i  ask a friend and told me that i should let the last line empty in every file. and it works  fine
