### ISSUE TITLE
SyntaxError when parsing html. 

### ISSUE THREAD

**Issue by intijk** [prettier/eslint-plugin-prettier#203] opened 2019-06-16 02:04 UTC
**What version of `eslint` are you using?**
v5.16.0

**What version of `prettier` are you using?**
1.18.2

**What version of `eslint-plugin-prettier` are you using?**
3.1.0

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
n/a

**What source code are you linting?**
html

**What did you expect to happen?**
corrent without throw

**What actually happened?**
prettier throw.

**How to reproduce this issue?**
```
git clone git@github.com:intijk/prettier_syntax_error.git
cd prettier_syntax_error/
yarn install
nodejs test.js
```

Some comment:
This is whether an issue of prettier or an issue or this plugin, 
I think @BPScott already aware of this one by :
> // prettier.format() may throw a SyntaxError if it cannot parse the 
> // source code it is given. Ususally for JS files this isn't a
> // problem as ESLint will report invalid syntax before trying to
> // pass it to the prettier plugin. However this might be a problem
> // for non-JS languages that are handled by a plugin. Notably Vue 
> // files throw an error if they contain unclosed elements, such as
> // `<template><div></template>`. In this case report an error at the 
> // point at which parsing failed.

Since prettier already [claim](https://prettier.io/blog/2018/11/07/1.15.0.html) support of html file, maybe we should fix it? 

I could move it to prettier issue if confirmed.

**Comment by BPScott** [comment] 2019-06-17 02:07
This repo is a plugin for ESLint that runs prettier as an ESLint rule. In your reproduction instructions you never install eslint, let alone run it. As such non of the code in this repo ever runs so I'm not sure what you're trying to demo to me :)

Your reproduction fails because you're telling prettier "hey try and parse `<!DOCTYPE html><html></html>` using the babylon parser" - the babylon parser parses javascript, not html and as that code isn't valid javascript prettier understandably falls over. If you want prettier to run over that file then you should remove the `parser: 'babylon'` option. Prettier will then infer the right parser to use based off the filepath option you gave it (in this case the html parser because your filename is test.html).

**Comment by BPScott** [comment] 2019-07-01 01:57
Closing as invalid as there wasn't any follow up. Please reopen if you've got more info

**Closed by BPScott** 2019-07-01 01:57 UTC
